services:
  db:
    container_name: libpostgre
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432

  myapp:
    build: .
    environment:
      PG_CONNECTION_STRING: postgres://myuser:mypassword@postgres/mydatabase
    ports:
      - "3000:3000" # Go uygulamasının çalıştığı portu dış dünyaya aç
    depends_on:
      - db
